{% set name = "cgroupspy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cgroupspy-{{ version }}.tar.gz
  sha256: 8ee941c7ab9234a0b17a81b0b26487f7f1031f78b7a24cdd8eed1b5fa5970496

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - cgroupspy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cloudsigma/cgroupspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for managing cgroups

  description: |
    Python library for managing cgroups

    The library provides a pythonic way to manage and represent cgroups.
    It provides interfaces that convert python objects to cgroups
    compatible strings and vise versa.
  dev_url: https://github.com/cloudsigma/cgroupspy

extra:
  recipe-maintainers:
    - xylar
    - sodre
