{% set name = "cgroupspy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cgroupspy-{{ version }}.tar.gz
  sha256: 2a9e578566b99ac05c452d23044ea3061c9f9445752360c2ce4e9f2439fa1577

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - cgroupspy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cloudsigma/cgroupspy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for managing cgroups

  description: |
    Python library for managing cgroups

    The library provides a pythonic way to manage and represent cgroups.
    It provides interfaces that convert python objects to cgroups
    compatible strings and vise versa.
  dev_url: https://github.com/cloudsigma/cgroupspy

extra:
  recipe-maintainers:
    - xylar
    - sodre
